
#ifndef MOTOR_H
#define MOTOR_H


#include "stm32f4xx_gpio.h"
#include "stm32f4xx_tim.h"
#include "config_pwm.h"
#include "define.h"
#include "config_port.h"
#include "calculate.h"
//#include "robot_information.h"
#include <math.h>


//STM基板のボックスコネクタ一番上から0、一番下が9
#define LEFT_F_TIRE		8	//1
#define LEFT_B_TIRE 	9	//2
#define RIGHT_F_TIRE	5
#define RIGHT_B_TIRE	4
#define TOP_RACKET_RELOAD_MOTOR	0//10
#define TOP_RACKET_RELEASE_MOTOR	1//9


#define LEFT_ARM1	0
#define LEFT_ARM2	0

#define SERVO_TIM_CH		MOTOR_7_TIM_CH
#define SERVO_PWM_SET		MOTOR_7_PWM_SET

#define RIGHT_ARM1		0
#define RIGHT_ARM1_PWM			MOTOR_0_PWM
#define RIGHT_ARM1_TIM_CH		MOTOR_0_TIM_CH
#define RIGHT_ARM1_PUSH			MOTOR_0_PIN0
#define RIGHT_ARM1_PULL			MOTOR_0_PIN1
#define RIGHT_ARM1_PWM_SET	MOTOR_0_PWM_SET

#define RIGHT_ARM2		1
#define RIGHT_ARM2_PWM			MOTOR_1_PWM
#define RIGHT_ARM2_TIM_CH		MOTOR_1_TIM_CH
#define RIGHT_ARM2_PUSH			MOTOR_1_PIN0
#define RIGHT_ARM2_PULL			MOTOR_1_PIN1
#define RIGHT_ARM2_PWM_SET	MOTOR_1_PWM_SET


//#define PWM_FREQUENCY	100000	//100kHzに設定

#define	MOTOR_0_PWM			GPIOB, GPIO_Pin_1
#define	MOTOR_0_TIM_CH		TIM8, 3
#define	MOTOR_0_PIN0			GPIOA, GPIO_Pin_7
#define	MOTOR_0_PIN1			GPIOC, GPIO_Pin_4
#define	MOTOR_0_PWM_SET	TIM8, MOTOR_0_PWM

#define	MOTOR_1_PWM			GPIOB, GPIO_Pin_0
#define	MOTOR_1_TIM_CH		TIM8, 2
#define	MOTOR_1_PIN0			GPIOA, GPIO_Pin_6
#define	MOTOR_1_PIN1			GPIOC, GPIO_Pin_5
#define	MOTOR_1_PWM_SET	TIM8, MOTOR_1_PWM

#define	MOTOR_2_PWM			GPIOE, GPIO_Pin_11
#define	MOTOR_2_TIM_CH		TIM1, 2
#define	MOTOR_2_PIN0			GPIOE, GPIO_Pin_4
#define	MOTOR_2_PIN1			GPIOE, GPIO_Pin_9
#define	MOTOR_2_PWM_SET	TIM1, MOTOR_2_PWM

#define	MOTOR_3_PWM			GPIOE, GPIO_Pin_5
#define	MOTOR_3_TIM_CH		TIM9, 1
#define	MOTOR_3_PIN0			GPIOE, GPIO_Pin_3
#define	MOTOR_3_PIN1			GPIOE, GPIO_Pin_2
#define	MOTOR_3_PWM_SET	TIM9, MOTOR_3_PWM

#define	MOTOR_4_PWM			GPIOE, GPIO_Pin_8
#define	MOTOR_4_TIM_CH		TIM1, 1
#define 	MOTOR_4_PIN0			GPIOB, GPIO_Pin_2
#define 	MOTOR_4_PIN1			GPIOE, GPIO_Pin_10
#define 	MOTOR_4_PWM_SET	TIM1, MOTOR_4_PWM

#define	MOTOR_5_PWM			GPIOA, GPIO_Pin_2
#define	MOTOR_5_TIM_CH		TIM2, 3
#define	MOTOR_5_PIN0			GPIOE, GPIO_Pin_6
#define	MOTOR_5_PIN1			GPIOE, GPIO_Pin_7
#define	MOTOR_5_PWM_SET	TIM1, MOTOR_5_PWM

#define	MOTOR_6_PWM			GPIOE, GPIO_Pin_14
#define	MOTOR_6_TIM_CH		TIM1, 4
#define	MOTOR_6_PIN0			GPIOB, GPIO_Pin_10
#define	MOTOR_6_PIN1			GPIOB, GPIO_Pin_12
#define	MOTOR_6_PWM_SET	TIM1, MOTOR_6_PWM

#define	MOTOR_7_PWM			GPIOE, GPIO_Pin_13
#define	MOTOR_7_TIM_CH		TIM1, 3
#define	MOTOR_7_PIN0			GPIOD, GPIO_Pin_12
#define	MOTOR_7_PIN1			GPIOE, GPIO_Pin_15
#define	MOTOR_7_PWM_SET	TIM1, MOTOR_7_PWM

#define	MOTOR_8_PWM			GPIOB, GPIO_Pin_11
#define	MOTOR_8_TIM_CH		TIM2, 4
#define	MOTOR_8_PIN0			GPIOB, GPIO_Pin_13
#define	MOTOR_8_PIN1			GPIOD, GPIO_Pin_10
#define 	MOTOR_8_PWM_SET	TIM2, MOTOR_8_PWM

#define	MOTOR_9_PWM			GPIOA, GPIO_Pin_15
#define	MOTOR_9_TIM_CH		TIM2, 1
#define	MOTOR_9_PIN0			GPIOD, GPIO_Pin_13
#define	MOTOR_9_PIN1			GPIOD, GPIO_Pin_11
#define	MOTOR_9_PWM_SET	TIM2, MOTOR_9_PWM

#define LEFT_ARM1_PWM			MOTOR_0_PWM
#define LEFT_ARM1_TIM_CH	MOTOR_0_TIM_CH
#define LEFT_ARM1_PUSH		MOTOR_0_PIN0
#define LEFT_ARM1_PULL			MOTOR_0_PIN1
#define LEFT_ARM1_PWM_SET	MOTOR_0_PWM_SET

/*
#if LEFT_ARM1 == 0
	#define LEFT_ARM1_PWM			MOTOR_0_PWM
	#define LEFT_ARM1_TIM_CH		MOTOR_0_TIM_CH
	#define LEFT_ARM1_PUSH				MOTOR_0_PIN0
	#define LEFT_ARM1_PULL			MOTOR_0_PIN1
	#define LEFT_ARM1_PWM_SET	MOTOR_0_PWM_SET
#elif LEFT_F_TIRE == 1
	#define LEFT_F_TIRE_PWM			MOTOR_1_PWM
	#define	LEFT_F_TIRE_TIM_CH		MOTOR_1_TIM_CH
	#define LEFT_F_TIRE_CW				MOTOR_1_PIN0
	#define LEFT_F_TIRE_CCW			MOTOR_1_PIN1
	#define LEFT_F_TIRE_PWM_SET	MOTOR_1_PWM_SET
#elif LEFT_F_TIRE == 2
	#define LEFT_F_TIRE_PWM			MOTOR_2_PWM
	#define	LEFT_F_TIRE_TIM_CH		MOTOR_2_TIM_CH
	#define LEFT_F_TIRE_CW				MOTOR_2_PIN0
	#define LEFT_F_TIRE_CCW			MOTOR_2_PIN1
	#define LEFT_F_TIRE_PWM_SET	MOTOR_2_PWM_SET
#elif LEFT_F_TIRE == 3
	#define LEFT_F_TIRE_PWM			MOTOR_3_PWM
	#define	LEFT_F_TIRE_TIM_CH		MOTOR_3_TIM_CH
	#define LEFT_F_TIRE_CW				MOTOR_3_PIN0
	#define LEFT_F_TIRE_CCW			MOTOR_3_PIN1
	#define LEFT_F_TIRE_PWM_SET	MOTOR_3_PWM_SET
#elif LEFT_F_TIRE == 4
	#define LEFT_F_TIRE_PWM			MOTOR_4_PWM
	#define	LEFT_F_TIRE_TIM_CH		MOTOR_4_TIM_CH
	#define LEFT_F_TIRE_CW				MOTOR_4_PIN0
	#define LEFT_F_TIRE_CCW			MOTOR_4_PIN1
	#define LEFT_F_TIRE_PWM_SET	MOTOR_4_PWM_SET
#elif LEFT_F_TIRE == 5
	#define LEFT_F_TIRE_PWM			MOTOR_5_PWM
	#define	LEFT_F_TIRE_TIM_CH		MOTOR_5_TIM_CH
	#define LEFT_F_TIRE_CW				MOTOR_5_PIN0
	#define LEFT_F_TIRE_CCW			MOTOR_5_PIN1
	#define LEFT_F_TIRE_PWM_SET	MOTOR_5_PWM_SET
#elif LEFT_F_TIRE == 6
	#define LEFT_F_TIRE_PWM			MOTOR_6_PWM
	#define	LEFT_F_TIRE_TIM_CH		MOTOR_6_TIM_CH
	#define LEFT_F_TIRE_CW				MOTOR_6_PIN0
	#define LEFT_F_TIRE_CCW			MOTOR_6_PIN1
	#define LEFT_F_TIRE_PWM_SET	MOTOR_6_PWM_SET
#elif LEFT_F_TIRE == 7
	#define LEFT_F_TIRE_PWM			MOTOR_7_PWM
	#define	LEFT_F_TIRE_TIM_CH		MOTOR_7_TIM_CH
	#define LEFT_F_TIRE_CW				MOTOR_7_PIN0
	#define LEFT_F_TIRE_CCW			MOTOR_7_PIN1
	#define LEFT_F_TIRE_PWM_SET	MOTOR_7_PWM_SET
#elif LEFT_F_TIRE == 8
	#define 	LEFT_F_TIRE_PWM			MOTOR_8_PWM
	#define	LEFT_F_TIRE_TIM_CH		MOTOR_8_TIM_CH
	#define LEFT_F_TIRE_CW				MOTOR_8_PIN0
	#define LEFT_F_TIRE_CCW			MOTOR_8_PIN1
	#define LEFT_F_TIRE_PWM_SET	MOTOR_8_PWM_SET
#elif LEFT_F_TIRE == 9
	#define LEFT_F_TIRE_PWM			MOTOR_9_PWM
	#define	LEFT_F_TIRE_TIM_CH		MOTOR_9_TIM_CH
	#define LEFT_F_TIRE_CW				MOTOR_9_PIN0
	#define LEFT_F_TIRE_CCW			MOTOR_9_PIN1
	#define LEFT_F_TIRE_PWM_SET	MOTOR_9_PWM_SET
#endif


#if LEFT_B_TIRE == 0
	#define LEFT_B_TIRE_PWM			MOTOR_0_PWM
	#define	LEFT_B_TIRE_TIM_CH	MOTOR_0_TIM_CH
	#define LEFT_B_TIRE_CW				MOTOR_0_PIN0
	#define LEFT_B_TIRE_CCW			MOTOR_0_PIN1
	#define LEFT_B_TIRE_PWM_SET	MOTOR_0_PWM_SET
#elif LEFT_B_TIRE == 1
	#define LEFT_B_TIRE_PWM			MOTOR_1_PWM
	#define	LEFT_B_TIRE_TIM_CH	MOTOR_1_TIM_CH
	#define LEFT_B_TIRE_CW				MOTOR_1_PIN0
	#define LEFT_B_TIRE_CCW			MOTOR_1_PIN1
	#define LEFT_B_TIRE_PWM_SET	MOTOR_1_PWM_SET
#elif LEFT_B_TIRE == 2
	#define LEFT_B_TIRE_PWM			MOTOR_2_PWM
	#define	LEFT_B_TIRE_TIM_CH	MOTOR_2_TIM_CH
	#define LEFT_B_TIRE_CW				MOTOR_2_PIN0
	#define LEFT_B_TIRE_CCW			MOTOR_2_PIN1
	#define LEFT_B_TIRE_PWM_SET	MOTOR_2_PWM_SET
#elif LEFT_B_TIRE == 3
	#define LEFT_B_TIRE_PWM			MOTOR_3_PWM
	#define	LEFT_B_TIRE_TIM_CH	MOTOR_3_TIM_CH
	#define LEFT_B_TIRE_CW				MOTOR_3_PIN0
	#define LEFT_B_TIRE_CCW			MOTOR_3_PIN1
	#define LEFT_B_TIRE_PWM_SET	MOTOR_3_PWM_SET
#elif LEFT_B_TIRE == 4
	#define LEFT_B_TIRE_PWM			MOTOR_4_PWM
	#define	LEFT_B_TIRE_TIM_CH	MOTOR_4_TIM_CH
	#define LEFT_B_TIRE_CW				MOTOR_4_PIN0
	#define LEFT_B_TIRE_CCW			MOTOR_4_PIN1
	#define LEFT_B_TIRE_PWM_SET	MOTOR_4_PWM_SET
#elif LEFT_B_TIRE == 5
	#define LEFT_B_TIRE_PWM			MOTOR_5_PWM
	#define	LEFT_B_TIRE_TIM_CH	MOTOR_5_TIM_CH
	#define LEFT_B_TIRE_CW				MOTOR_5_PIN0
	#define LEFT_B_TIRE_CCW			MOTOR_5_PIN1
	#define LEFT_B_TIRE_PWM_SET	MOTOR_5_PWM_SET
#elif LEFT_B_TIRE == 6
	#define LEFT_B_TIRE_PWM			MOTOR_6_PWM
	#define	LEFT_B_TIRE_TIM_CH	MOTOR_6_TIM_CH
	#define LEFT_B_TIRE_CW				MOTOR_6_PIN0
	#define LEFT_B_TIRE_CCW			MOTOR_6_PIN1
	#define LEFT_B_TIRE_PWM_SET	MOTOR_6_PWM_SET
#elif LEFT_B_TIRE == 7
	#define LEFT_B_TIRE_PWM			MOTOR_7_PWM
	#define	LEFT_B_TIRE_TIM_CH	MOTOR_7_TIM_CH
	#define LEFT_B_TIRE_CW				MOTOR_7_PIN0
	#define LEFT_B_TIRE_CCW			MOTOR_7_PIN1
	#define LEFT_B_TIRE_PWM_SET	MOTOR_7_PWM_SET
#elif LEFT_B_TIRE == 8
	#define LEFT_B_TIRE_PWM			MOTOR_8_PWM
	#define	LEFT_B_TIRE_TIM_CH	MOTOR_8_TIM_CH
	#define LEFT_B_TIRE_CW				MOTOR_8_PIN0
	#define LEFT_B_TIRE_CCW			MOTOR_8_PIN1
	#define LEFT_B_TIRE_PWM_SET	MOTOR_8_PWM_SET
#elif LEFT_B_TIRE == 9
	#define LEFT_B_TIRE_PWM			MOTOR_9_PWM
	#define	LEFT_B_TIRE_TIM_CH		MOTOR_9_TIM_CH
	#define LEFT_B_TIRE_CW			MOTOR_9_PIN0
	#define LEFT_B_TIRE_CCW			MOTOR_9_PIN1
	#define LEFT_B_TIRE_PWM_SET		MOTOR_9_PWM_SET
#endif

#if RIGHT_F_TIRE == 0
	#define RIGHT_F_TIRE_PWM			MOTOR_0_PWM
	#define	RIGHT_F_TIRE_TIM_CH		MOTOR_0_TIM_CH
	#define RIGHT_F_TIRE_CW			MOTOR_0_PIN0
	#define RIGHT_F_TIRE_CCW			MOTOR_0_PIN1
	#define RIGHT_F_TIRE_PWM_SET		MOTOR_0_PWM_SET
#elif RIGHT_F_TIRE == 1
	#define RIGHT_F_TIRE_PWM			MOTOR_1_PWM
	#define	RIGHT_F_TIRE_TIM_CH		MOTOR_1_TIM_CH
	#define RIGHT_F_TIRE_CW			MOTOR_1_PIN0
	#define RIGHT_F_TIRE_CCW			MOTOR_1_PIN1
	#define RIGHT_F_TIRE_PWM_SET		MOTOR_1_PWM_SET
#elif RIGHT_F_TIRE == 2
	#define RIGHT_F_TIRE_PWM			MOTOR_2_PWM
	#define	RIGHT_F_TIRE_TIM_CH		MOTOR_2_TIM_CH
	#define RIGHT_F_TIRE_CW			MOTOR_2_PIN0
	#define RIGHT_F_TIRE_CCW			MOTOR_2_PIN1
	#define RIGHT_F_TIRE_PWM_SET		MOTOR_2_PWM_SET
#elif RIGHT_F_TIRE == 3
	#define RIGHT_F_TIRE_PWM			MOTOR_3_PWM
	#define	RIGHT_F_TIRE_TIM_CH		MOTOR_3_TIM_CH
	#define RIGHT_F_TIRE_CW			MOTOR_3_PIN0
	#define RIGHT_F_TIRE_CCW			MOTOR_3_PIN1
	#define RIGHT_F_TIRE_PWM_SET		MOTOR_3_PWM_SET
#elif RIGHT_F_TIRE == 4
	#define RIGHT_F_TIRE_PWM			MOTOR_4_PWM
	#define	RIGHT_F_TIRE_TIM_CH		MOTOR_4_TIM_CH
	#define RIGHT_F_TIRE_CW			MOTOR_4_PIN0
	#define RIGHT_F_TIRE_CCW			MOTOR_4_PIN1
	#define RIGHT_F_TIRE_PWM_SET		MOTOR_4_PWM_SET
#elif RIGHT_F_TIRE == 5
	#define RIGHT_F_TIRE_PWM			MOTOR_5_PWM
	#define	RIGHT_F_TIRE_TIM_CH		MOTOR_5_TIM_CH
	#define RIGHT_F_TIRE_CW			MOTOR_5_PIN0
	#define RIGHT_F_TIRE_CCW			MOTOR_5_PIN1
	#define RIGHT_F_TIRE_PWM_SET		MOTOR_5_PWM_SET
#elif RIGHT_F_TIRE == 6
	#define RIGHT_F_TIRE_PWM			MOTOR_6_PWM
	#define	RIGHT_F_TIRE_TIM_CH		MOTOR_6_TIM_CH
	#define RIGHT_F_TIRE_CW			MOTOR_6_PIN0
	#define RIGHT_F_TIRE_CCW			MOTOR_6_PIN1
	#define RIGHT_F_TIRE_PWM_SET		MOTOR_6_PWM_SET
#elif RIGHT_F_TIRE == 7
	#define RIGHT_F_TIRE_PWM			MOTOR_7_PWM
	#define	RIGHT_F_TIRE_TIM_CH		MOTOR_7_TIM_CH
	#define RIGHT_F_TIRE_CW			MOTOR_7_PIN0
	#define RIGHT_F_TIRE_CCW			MOTOR_7_PIN1
	#define RIGHT_F_TIRE_PWM_SET		MOTOR_7_PWM_SET
#elif RIGHT_F_TIRE == 8
	#define RIGHT_F_TIRE_PWM			MOTOR_8_PWM
	#define	RIGHT_F_TIRE_TIM_CH		MOTOR_8_TIM_CH
	#define RIGHT_F_TIRE_CW			MOTOR_8_PIN0
	#define RIGHT_F_TIRE_CCW			MOTOR_8_PIN1
	#define RIGHT_F_TIRE_PWM_SET		MOTOR_8_PWM_SET
#elif RIGHT_F_TIRE == 9
	#define RIGHT_F_TIRE_PWM			MOTOR_9_PWM
	#define	RIGHT_F_TIRE_TIM_CH		MOTOR_9_TIM_CH
	#define RIGHT_F_TIRE_CW			MOTOR_9_PIN0
	#define RIGHT_F_TIRE_CCW			MOTOR_9_PIN1
	#define RIGHT_F_TIRE_PWM_SET		MOTOR_9_PWM_SET
#endif


#if RIGHT_B_TIRE == 0
	#define RIGHT_B_TIRE_PWM			MOTOR_0_PWM
	#define	RIGHT_B_TIRE_TIM_CH		MOTOR_0_TIM_CH
	#define RIGHT_B_TIRE_CW			MOTOR_0_PIN0
	#define RIGHT_B_TIRE_CCW			MOTOR_0_PIN1
	#define RIGHT_B_TIRE_PWM_SET		MOTOR_0_PWM_SET
#elif RIGHT_B_TIRE == 1
	#define RIGHT_B_TIRE_PWM			MOTOR_1_PWM
	#define	RIGHT_B_TIRE_TIM_CH		MOTOR_1_TIM_CH
	#define RIGHT_B_TIRE_CW			MOTOR_1_PIN0
	#define RIGHT_B_TIRE_CCW			MOTOR_1_PIN1
	#define RIGHT_B_TIRE_PWM_SET		MOTOR_1_PWM_SET
#elif RIGHT_B_TIRE == 2
	#define RIGHT_B_TIRE_PWM			MOTOR_2_PWM
	#define	RIGHT_B_TIRE_TIM_CH		MOTOR_2_TIM_CH
	#define RIGHT_B_TIRE_CW			MOTOR_2_PIN0
	#define RIGHT_B_TIRE_CCW			MOTOR_2_PIN1
	#define RIGHT_B_TIRE_PWM_SET		MOTOR_2_PWM_SET
#elif RIGHT_B_TIRE == 3
	#define RIGHT_B_TIRE_PWM			MOTOR_3_PWM
	#define	RIGHT_B_TIRE_TIM_CH		MOTOR_3_TIM_CH
	#define RIGHT_B_TIRE_CW			MOTOR_3_PIN0
	#define RIGHT_B_TIRE_CCW			MOTOR_3_PIN1
	#define RIGHT_B_TIRE_PWM_SET		MOTOR_3_PWM_SET
#elif RIGHT_B_TIRE == 4
	#define RIGHT_B_TIRE_PWM			MOTOR_4_PWM
	#define	RIGHT_B_TIRE_TIM_CH		MOTOR_4_TIM_CH
	#define RIGHT_B_TIRE_CW			MOTOR_4_PIN0
	#define RIGHT_B_TIRE_CCW			MOTOR_4_PIN1
	#define RIGHT_B_TIRE_PWM_SET		MOTOR_4_PWM_SET
#elif RIGHT_B_TIRE == 5
	#define RIGHT_B_TIRE_PWM			MOTOR_5_PWM
	#define	RIGHT_B_TIRE_TIM_CH		MOTOR_5_TIM_CH
	#define RIGHT_B_TIRE_CW			MOTOR_5_PIN0
	#define RIGHT_B_TIRE_CCW			MOTOR_5_PIN1
	#define RIGHT_B_TIRE_PWM_SET		MOTOR_5_PWM_SET
#elif RIGHT_B_TIRE == 6
	#define RIGHT_B_TIRE_PWM			MOTOR_6_PWM
	#define	RIGHT_B_TIRE_TIM_CH		MOTOR_6_TIM_CH
	#define RIGHT_B_TIRE_CW			MOTOR_6_PIN0
	#define RIGHT_B_TIRE_CCW			MOTOR_6_PIN1
	#define RIGHT_B_TIRE_PWM_SET		MOTOR_6_PWM_SET
#elif RIGHT_B_TIRE == 7
	#define RIGHT_B_TIRE_PWM			MOTOR_7_PWM
	#define	RIGHT_B_TIRE_TIM_CH		MOTOR_7_TIM_CH
	#define RIGHT_B_TIRE_CW			MOTOR_7_PIN0
	#define RIGHT_B_TIRE_CCW			MOTOR_7_PIN1
	#define RIGHT_B_TIRE_PWM_SET		MOTOR_7_PWM_SET
#elif RIGHT_B_TIRE == 8
	#define RIGHT_B_TIRE_PWM			MOTOR_8_PWM
	#define	RIGHT_B_TIRE_TIM_CH		MOTOR_8_TIM_CH
	#define RIGHT_B_TIRE_CW			MOTOR_8_PIN0
	#define RIGHT_B_TIRE_CCW			MOTOR_8_PIN1
	#define RIGHT_B_TIRE_PWM_SET		MOTOR_8_PWM_SET
#elif RIGHT_B_TIRE == 9
	#define RIGHT_B_TIRE_PWM			MOTOR_9_PWM
	#define	RIGHT_B_TIRE_TIM_CH		MOTOR_9_TIM_CH
	#define RIGHT_B_TIRE_CW			MOTOR_9_PIN0
	#define RIGHT_B_TIRE_CCW			MOTOR_9_PIN1
	#define RIGHT_B_TIRE_PWM_SET		MOTOR_9_PWM_SET
#endif


#if TOP_RACKET_RELOAD_MOTOR == 0
	#define TOP_RACKET_RELOAD_MOTOR_PWM			MOTOR_0_PWM
	#define	TOP_RACKET_RELOAD_MOTOR_TIM_CH		MOTOR_0_TIM_CH
	#define TOP_RACKET_RELOAD_MOTOR_CW			MOTOR_0_PIN0
	#define TOP_RACKET_RELOAD_MOTOR_CCW			MOTOR_0_PIN1
	#define TOP_RACKET_RELOAD_MOTOR_PWM_SET		MOTOR_0_PWM_SET
#elif TOP_RACKET_RELOAD_MOTOR == 1
	#define TOP_RACKET_RELOAD_MOTOR_PWM			MOTOR_1_PWM
	#define	TOP_RACKET_RELOAD_MOTOR_TIM_CH		MOTOR_1_TIM_CH
	#define TOP_RACKET_RELOAD_MOTOR_CW			MOTOR_1_PIN0
	#define TOP_RACKET_RELOAD_MOTOR_CCW			MOTOR_1_PIN1
	#define TOP_RACKET_RELOAD_MOTOR_PWM_SET		MOTOR_1_PWM_SET
#elif TOP_RACKET_RELOAD_MOTOR == 2
	#define TOP_RACKET_RELOAD_MOTOR_PWM			MOTOR_2_PWM
	#define	TOP_RACKET_RELOAD_MOTOR_TIM_CH		MOTOR_2_TIM_CH
	#define TOP_RACKET_RELOAD_MOTOR_CW			MOTOR_2_PIN0
	#define TOP_RACKET_RELOAD_MOTOR_CCW			MOTOR_2_PIN1
	#define TOP_RACKET_RELOAD_MOTOR_PWM_SET		MOTOR_2_PWM_SET
#elif TOP_RACKET_RELOAD_MOTOR == 3
	#define TOP_RACKET_RELOAD_MOTOR_PWM			MOTOR_3_PWM
	#define	TOP_RACKET_RELOAD_MOTOR_TIM_CH		MOTOR_3_TIM_CH
	#define TOP_RACKET_RELOAD_MOTOR_CW			MOTOR_3_PIN0
	#define TOP_RACKET_RELOAD_MOTOR_CCW			MOTOR_3_PIN1
	#define TOP_RACKET_RELOAD_MOTOR_PWM_SET		MOTOR_3_PWM_SET
#elif TOP_RACKET_RELOAD_MOTOR == 4
	#define TOP_RACKET_RELOAD_MOTOR_PWM			MOTOR_4_PWM
	#define	TOP_RACKET_RELOAD_MOTOR_TIM_CH		MOTOR_4_TIM_CH
	#define TOP_RACKET_RELOAD_MOTOR_CW			MOTOR_4_PIN0
	#define TOP_RACKET_RELOAD_MOTOR_CCW			MOTOR_4_PIN1
	#define TOP_RACKET_RELOAD_MOTOR_PWM_SET		MOTOR_4_PWM_SET
#elif TOP_RACKET_RELOAD_MOTOR == 5
	#define TOP_RACKET_RELOAD_MOTOR_PWM			MOTOR_5_PWM
	#define	TOP_RACKET_RELOAD_MOTOR_TIM_CH		MOTOR_5_TIM_CH
	#define TOP_RACKET_RELOAD_MOTOR_CW			MOTOR_5_PIN0
	#define TOP_RACKET_RELOAD_MOTOR_CCW			MOTOR_5_PIN1
	#define TOP_RACKET_RELOAD_MOTOR_PWM_SET		MOTOR_5_PWM_SET
#elif TOP_RACKET_RELOAD_MOTOR == 6
	#define TOP_RACKET_RELOAD_MOTOR_PWM			MOTOR_6_PWM
	#define	TOP_RACKET_RELOAD_MOTOR_TIM_CH		MOTOR_6_TIM_CH
	#define TOP_RACKET_RELOAD_MOTOR_CW			MOTOR_6_PIN0
	#define TOP_RACKET_RELOAD_MOTOR_CCW			MOTOR_6_PIN1
	#define TOP_RACKET_RELOAD_MOTOR_PWM_SET		MOTOR_6_PWM_SET
#elif TOP_RACKET_RELOAD_MOTOR == 7
	#define TOP_RACKET_RELOAD_MOTOR_PWM			MOTOR_7_PWM
	#define	TOP_RACKET_RELOAD_MOTOR_TIM_CH		MOTOR_7_TIM_CH
	#define TOP_RACKET_RELOAD_MOTOR_CW			MOTOR_7_PIN0
	#define TOP_RACKET_RELOAD_MOTOR_CCW			MOTOR_7_PIN1
	#define TOP_RACKET_RELOAD_MOTOR_PWM_SET		MOTOR_7_PWM_SET
#elif TOP_RACKET_RELOAD_MOTOR == 8
	#define TOP_RACKET_RELOAD_MOTOR_PWM			MOTOR_8_PWM
	#define	TOP_RACKET_RELOAD_MOTOR_TIM_CH		MOTOR_8_TIM_CH
	#define TOP_RACKET_RELOAD_MOTOR_CW			MOTOR_8_PIN0
	#define TOP_RACKET_RELOAD_MOTOR_CCW			MOTOR_8_PIN1
	#define TOP_RACKET_RELOAD_MOTOR_PWM_SET		MOTOR_8_PWM_SET
#elif TOP_RACKET_RELOAD_MOTOR == 9
	#define TOP_RACKET_RELOAD_MOTOR_PWM			MOTOR_9_PWM
	#define	TOP_RACKET_RELOAD_MOTOR_TIM_CH		MOTOR_9_TIM_CH
	#define TOP_RACKET_RELOAD_MOTOR_CW			MOTOR_9_PIN0
	#define TOP_RACKET_RELOAD_MOTOR_CCW			MOTOR_9_PIN1
	#define TOP_RACKET_RELOAD_MOTOR_PWM_SET		MOTOR_9_PWM_SET
#endif

#if TOP_RACKET_RELEASE_MOTOR == 0
	#define TOP_RACKET_RELEASE_MOTOR_PWM			MOTOR_0_PWM
	#define	TOP_RACKET_RELEASE_MOTOR_TIM_CH		MOTOR_0_TIM_CH
	#define TOP_RACKET_RELEASE_MOTOR_CW			MOTOR_0_PIN0
	#define TOP_RACKET_RELEASE_MOTOR_CCW			MOTOR_0_PIN1
	#define TOP_RACKET_RELEASE_MOTOR_PWM_SET		MOTOR_0_PWM_SET
#elif TOP_RACKET_RELEASE_MOTOR == 1
	#define TOP_RACKET_RELEASE_MOTOR_PWM			MOTOR_1_PWM
	#define	TOP_RACKET_RELEASE_MOTOR_TIM_CH		MOTOR_1_TIM_CH
	#define TOP_RACKET_RELEASE_MOTOR_CW			MOTOR_1_PIN0
	#define TOP_RACKET_RELEASE_MOTOR_CCW			MOTOR_1_PIN1
	#define TOP_RACKET_RELEASE_MOTOR_PWM_SET		MOTOR_1_PWM_SET
#elif TOP_RACKET_RELEASE_MOTOR == 2
	#define TOP_RACKET_RELEASE_MOTOR_PWM			MOTOR_2_PWM
	#define	TOP_RACKET_RELEASE_MOTOR_TIM_CH		MOTOR_2_TIM_CH
	#define TOP_RACKET_RELEASE_MOTOR_CW			MOTOR_2_PIN0
	#define TOP_RACKET_RELEASE_MOTOR_CCW			MOTOR_2_PIN1
	#define TOP_RACKET_RELEASE_MOTOR_PWM_SET		MOTOR_2_PWM_SET
#elif TOP_RACKET_RELEASE_MOTOR == 3
	#define TOP_RACKET_RELEASE_MOTOR_PWM			MOTOR_3_PWM
	#define	TOP_RACKET_RELEASE_MOTOR_TIM_CH		MOTOR_3_TIM_CH
	#define TOP_RACKET_RELEASE_MOTOR_CW			MOTOR_3_PIN0
	#define TOP_RACKET_RELEASE_MOTOR_CCW			MOTOR_3_PIN1
	#define TOP_RACKET_RELEASE_MOTOR_PWM_SET		MOTOR_3_PWM_SET
#elif TOP_RACKET_RELEASE_MOTOR == 4
	#define TOP_RACKET_RELEASE_MOTOR_PWM			MOTOR_4_PWM
	#define	TOP_RACKET_RELEASE_MOTOR_TIM_CH		MOTOR_4_TIM_CH
	#define TOP_RACKET_RELEASE_MOTOR_CW			MOTOR_4_PIN0
	#define TOP_RACKET_RELEASE_MOTOR_CCW			MOTOR_4_PIN1
	#define TOP_RACKET_RELEASE_MOTOR_PWM_SET		MOTOR_4_PWM_SET
#elif TOP_RACKET_RELEASE_MOTOR == 5
	#define TOP_RACKET_RELEASE_MOTOR_PWM			MOTOR_5_PWM
	#define	TOP_RACKET_RELEASE_MOTOR_TIM_CH		MOTOR_5_TIM_CH
	#define TOP_RACKET_RELEASE_MOTOR_CW			MOTOR_5_PIN0
	#define TOP_RACKET_RELEASE_MOTOR_CCW			MOTOR_5_PIN1
	#define TOP_RACKET_RELEASE_MOTOR_PWM_SET		MOTOR_5_PWM_SET
#elif TOP_RACKET_RELEASE_MOTOR == 6
	#define TOP_RACKET_RELEASE_MOTOR_PWM			MOTOR_6_PWM
	#define	TOP_RACKET_RELEASE_MOTOR_TIM_CH		MOTOR_6_TIM_CH
	#define TOP_RACKET_RELEASE_MOTOR_CW			MOTOR_6_PIN0
	#define TOP_RACKET_RELEASE_MOTOR_CCW			MOTOR_6_PIN1
	#define TOP_RACKET_RELEASE_MOTOR_PWM_SET		MOTOR_6_PWM_SET
#elif TOP_RACKET_RELEASE_MOTOR == 7
	#define TOP_RACKET_RELEASE_MOTOR_PWM			MOTOR_7_PWM
	#define	TOP_RACKET_RELEASE_MOTOR_TIM_CH		MOTOR_7_TIM_CH
	#define TOP_RACKET_RELEASE_MOTOR_CW			MOTOR_7_PIN0
	#define TOP_RACKET_RELEASE_MOTOR_CCW			MOTOR_7_PIN1
	#define TOP_RACKET_RELEASE_MOTOR_PWM_SET		MOTOR_7_PWM_SET
#elif TOP_RACKET_RELEASE_MOTOR == 8
	#define TOP_RACKET_RELEASE_MOTOR_PWM			MOTOR_8_PWM
	#define	TOP_RACKET_RELEASE_MOTOR_TIM_CH		MOTOR_8_TIM_CH
	#define TOP_RACKET_RELEASE_MOTOR_CW			MOTOR_8_PIN0
	#define TOP_RACKET_RELEASE_MOTOR_CCW			MOTOR_8_PIN1
	#define TOP_RACKET_RELEASE_MOTOR_PWM_SET		MOTOR_8_PWM_SET
#elif TOP_RACKET_RELEASE_MOTOR == 9
	#define TOP_RACKET_RELEASE_MOTOR_PWM			MOTOR_9_PWM
	#define	TOP_RACKET_RELEASE_MOTOR_TIM_CH		MOTOR_9_TIM_CH
	#define TOP_RACKET_RELEASE_MOTOR_CW			MOTOR_9_PIN0
	#define TOP_RACKET_RELEASE_MOTOR_CCW			MOTOR_9_PIN1
	#define TOP_RACKET_RELEASE_MOTOR_PWM_SET		MOTOR_9_PWM_SET
#endif
*/

void Move_left_f_tire(float duty);
void Move_left_b_tire(float duty);
void Move_right_f_tire(float duty);
void Move_right_b_tire(float duty);
void Move_top_racket_RELEASE_motor(float duty);
void Move_top_racket_release_motor(float duty);

//void Move_result(Underbody_tire_t result);
void Move(float l_f_duty, float l_b_duty, float r_f_duty, float r_b_duty);

void Move_motor_0(float duty);
void Move_motor_1(float duty);
void Move_motor_2(float duty);
void Move_motor_3(float duty);
void Move_motor_4(float duty);
void Move_motor_5(float duty);
void Move_motor_6(float duty);
void Move_motor_7(float duty);
void Move_motor_8(float duty);
void Move_motor_9(float duty);
void Move_motor_number(float duty, unsigned char number);

void Deadtime_motor_0(void);
void Deadtime_motor_1(void);
void Deadtime_motor_2(void);
void Deadtime_motor_3(void);
void Deadtime_motor_4(void);
void Deadtime_motor_5(void);
void Deadtime_motor_6(void);
void Deadtime_motor_7(void);
void Deadtime_motor_8(void);
void Deadtime_motor_9(void);
void Deadtime_motor_number(unsigned char number);

void Deadtime_left_f_tire(void);
void Deadtime_left_b_tire(void);
void Deadtime_right_f_tire(void);
void Deadtime_right_b_tire(void);
void Deadtime_top_racket_RELEASE_motor(void);
void Deadtime_top_racket_release_motor(void);
void Deadtime_racket_motor(void);
void Deadtime_tire(void);
void Deadtime_all(void);

float get_motor_output_x(float motor_output, float degree);
float get_motor_output_y(float motor_output, float degree);
float get_motor_output_l_f(float motor_output_x, float motor_output_y, float degree_now);
float get_motor_output_l_b(float motor_output_x, float motor_output_y, float degree_now);
float get_motor_output_r_f(float motor_output_x, float motor_output_y, float degree_now);
float get_motor_output_r_b(float motor_output_x, float motor_output_y, float degree_now);

#endif
